/*
 * This source file was generated by the Gradle 'init' task
 */
package hexic;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


public class App {

    private static JFrame frame;

    private static void createAndShowGUI() {
        //Create and set up the window.
        frame = new JFrame("TopLevelDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create the menu bar.  Make it have a green background.
        JMenuBar menuBar = new JMenuBar();
        menuBar.setOpaque(true);

        //Set the menu bar and add the label to the content pane.
        frame.setJMenuBar(menuBar);
        HexicPanel hexicPanel = new HexicPanel();
        frame.add(hexicPanel);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
